/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.compras;

import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import mobiliario.ApplicationConstants;
import model.Articulo;
import model.Compra;
import services.ComprasService;
import services.ContabilidadServices;
import services.SystemService;

/**
 *
 * @author Gerardo Torreblanca
 */
public class AgregarCompraFormDialog extends java.awt.Dialog {
    
    ContabilidadServices contabilidadServices = new ContabilidadServices();
    private final SystemService systemService = SystemService.getInstance();
    private final ComprasService comprasService = new ComprasService();
    public static Articulo articulo = null;
   
    private static final DecimalFormat decimalFormat = new DecimalFormat( "#,###,###,##0.00" );
    public static boolean isContabilidadForm = false;
 

   
    public AgregarCompraFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        
        this.setTitle("Agregar compra");
        this.txtArticulo.setEnabled(false);
        this.txtCantidad.requestFocus();
        this.txtArticulo.setText(articulo.getDescripcion() +" "+articulo.getColor().getColor());
        llenar_tabla_compras(100);
      
    }
    
    public void llenar_tabla_compras(Integer limit){
        formato_tabla_compras();
        List<Compra> compras = comprasService.obtenerComprasPorArticuloId(false, articulo.getArticuloId(),limit);
        
        if(compras == null || compras.size()<0){
            return;
        }
        for(Compra compra : compras){
           
            DefaultTableModel temp = (DefaultTableModel) tablaCompras.getModel();
            
            Object fila[] = {
                compra.getId(),
                compra.getIdArticulo(),
                compra.getCantidad(),
                compra.getPrecioCompra(),
                compra.getComentario(),
                compra.getCreado(),
                compra.getActualizado()
            };
            temp.addRow(fila);
        } // end for compras
        
    }
    
     public void formato_tabla_compras(){
        Object[][] data = {{"","","","", "","",""}};
        String[] columNames = {"id","articuloId", "cantidad","precio compra","comentario","creado","actualizado"};
        DefaultTableModel tableModel = new DefaultTableModel(data, columNames);
        tablaCompras.setModel(tableModel);
        
        TableRowSorter<TableModel> ordenarTabla = new TableRowSorter<TableModel>(tableModel); 
        tablaCompras.setRowSorter(ordenarTabla);
        
        int[] anchos = {10,10, 30,30,100,40,40};

        for (int inn = 0; inn < tablaCompras.getColumnCount(); inn++) {
            tablaCompras.getColumnModel().getColumn(inn).setPreferredWidth(anchos[inn]);
        }
        
         try {
            DefaultTableModel temp = (DefaultTableModel) tablaCompras.getModel();
            temp.removeRow(temp.getRowCount() - 1);
        } catch (ArrayIndexOutOfBoundsException e) {
            ;
        }      
     
        DefaultTableCellRenderer centrar = new DefaultTableCellRenderer();
        centrar.setHorizontalAlignment(SwingConstants.CENTER);
        
        tablaCompras.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaCompras.getColumnModel().getColumn(0).setMinWidth(0);
        tablaCompras.getColumnModel().getColumn(0).setPreferredWidth(0);
        
         tablaCompras.getColumnModel().getColumn(1).setMaxWidth(0);
        tablaCompras.getColumnModel().getColumn(1).setMinWidth(0);
        tablaCompras.getColumnModel().getColumn(1).setPreferredWidth(0);
      
        tablaCompras.getColumnModel().getColumn(2).setCellRenderer(centrar);
        tablaCompras.getColumnModel().getColumn(3).setCellRenderer(centrar);
        tablaCompras.getColumnModel().getColumn(4).setCellRenderer(centrar);
        tablaCompras.getColumnModel().getColumn(5).setCellRenderer(centrar);
        tablaCompras.getColumnModel().getColumn(6).setCellRenderer(centrar);
      
      
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        radioLimitTodos = new javax.swing.JRadioButton();
        radioLimit101 = new javax.swing.JRadioButton();
        radioLimit1000 = new javax.swing.JRadioButton();
        btnMostrarLimit = new javax.swing.JButton();

        setTitle("Faltantes/Devolucion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Articulo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 110, 20));

        txtArticulo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Precio compra:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        txtPrecioCompra.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtComentario.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 300, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Comentario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCompras);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 530, 310));

        buttonGroup1.add(radioLimitTodos);
        radioLimitTodos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioLimitTodos.setText("Mostrar todos");
        radioLimitTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLimitTodosActionPerformed(evt);
            }
        });
        jPanel3.add(radioLimitTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        buttonGroup1.add(radioLimit101);
        radioLimit101.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioLimit101.setText("Últimos 100 registros");
        radioLimit101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLimit101ActionPerformed(evt);
            }
        });
        jPanel3.add(radioLimit101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buttonGroup1.add(radioLimit1000);
        radioLimit1000.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioLimit1000.setText("Últimos 1,000 registros");
        radioLimit1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLimit1000ActionPerformed(evt);
            }
        });
        jPanel3.add(radioLimit1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnMostrarLimit.setText("Mostrar");
        btnMostrarLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarLimitActionPerformed(evt);
            }
        });
        jPanel3.add(btnMostrarLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 550, 380));

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
//        inventario.validar_colores = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        
        try{
            
            if(!validateForm()){
                return;
            }
            
            Compra compra = new Compra();
            compra.setIdArticulo(articulo.getArticuloId());
            compra.setArticulo(articulo);
            compra.setComentario(this.txtComentario.getText());
            compra.setCantidad(new Float(this.txtCantidad.getText()));
            compra.setPrecioCompra(new Float(this.txtPrecioCompra.getText()));
            comprasService.insertCompra(compra);
            
            JOptionPane.showMessageDialog(null, ApplicationConstants.MESSAGE_SAVE_SUCCESSFUL, "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error, al obtener cantidad o precio compra ", "Error", JOptionPane.ERROR_MESSAGE);
           
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error, ocurrio un error inesperado\n"+e, "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void radioLimitTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLimitTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLimitTodosActionPerformed

    private void radioLimit101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLimit101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLimit101ActionPerformed

    private void radioLimit1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLimit1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLimit1000ActionPerformed

    private void btnMostrarLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarLimitActionPerformed
        
        Integer limit = null;
        if(this.radioLimit101.isSelected()){
            limit = 100;
        }else if(this.radioLimit1000.isSelected()){
            limit = 1000;
        }else if(this.radioLimitTodos.isSelected()){
            limit = null;
        }
        
        this.llenar_tabla_compras(limit);
        
    }//GEN-LAST:event_btnMostrarLimitActionPerformed
       
     public boolean validateForm(){
         
         StringBuilder message = new StringBuilder();
         int cont = 0;
         
         if(this.txtCantidad.getText().equals("")){
             message.append(++cont);
             message.append(". Cantidad no puede ir vacio\n");
         }
         if(this.txtPrecioCompra.getText().equals("")){
             message.append(++cont);
             message.append(". Precio compra no puede ir vacio\n");
         }
       
         if(!message.toString().equals("")){
             JOptionPane.showMessageDialog(null, message.toString(), "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }else{
             return true;
         }  
     
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarCompraFormDialog dialog = new AgregarCompraFormDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarLimit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioLimit1000;
    private javax.swing.JRadioButton radioLimit101;
    private javax.swing.JRadioButton radioLimitTodos;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtPrecioCompra;
    // End of variables declaration//GEN-END:variables
}
