package mobiliario;

import forms.inventario.InventarioForm;
import services.SaleService;
import clases.sqlclass;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import common.model.DetalleRenta;
import common.model.Renta;
import services.ItemService;
import services.SystemService;

/**
 *
 * @author Gerardo Torreblanca
 */
public class AsignarFaltante extends java.awt.Dialog {

    sqlclass funcion = new sqlclass();
    
    Object[][] dtconduc;      
    SaleService saleService;
    ItemService itemService = ItemService.getInstance();
    public static int g_articuloId;
    public static int g_rentaId;
    public static String g_descripcionArticulo;
    
    public String conviertemoneda(String valor) {

        DecimalFormatSymbols simbolo = new DecimalFormatSymbols();
        simbolo.setDecimalSeparator('.');
        simbolo.setGroupingSeparator(',');

        float entero = Float.parseFloat(valor);
        DecimalFormat formateador = new DecimalFormat("###,###.##", simbolo);
        String entero2 = formateador.format(entero);

        if (entero2.contains(".")) {
            entero2 = "$" + entero2;

        } else {
            entero2 = "$" + entero2 + ".00";
        }

        return entero2;
    }
    public AsignarFaltante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        saleService = SaleService.getInstance();
        funcion.conectate();
        this.setLocationRelativeTo(null);        
        this.setTitle("Asignar faltante ");   
        this.g_articuloId = InventarioForm.g_articuloId;
        this.txtDescripcionArticulo.setText(InventarioForm.g_descripcionArticulo);
      
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtDescripcionArticulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        checkAccidenteLaboral = new javax.swing.JCheckBox();

        setTitle("Faltantes/Devolucion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar faltante"));

        txtDescripcionArticulo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDescripcionArticulo.setToolTipText("");
        txtDescripcionArticulo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Articulo:");

        txtFolio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtFolio.setToolTipText("");
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFolioKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Folio:");

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Asignar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkAccidenteLaboral.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        checkAccidenteLaboral.setText("Por accidente de trabajo");
        checkAccidenteLaboral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkAccidenteLaboral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAccidenteLaboralMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(checkAccidenteLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtDescripcionArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAccidenteLaboral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 190));

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
//        InventarioForm.validar_colores = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
     public void mostrar_faltantes() {
        VerFaltantes ventana_faltantes = new VerFaltantes(null, true);
        ventana_faltantes.setVisible(true);
        ventana_faltantes.setLocationRelativeTo(null);
    }   
     
     public void asignarFaltante(){
        String folio = this.txtFolio.getText();
        Renta renta = null;
        boolean articuloEncontrado = false;
        
        if(!folio.equals("") && !this.checkAccidenteLaboral.isSelected()){           
            try {
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("folio", folio);
                List<Renta> rentas = saleService.obtenerRentasPorParametros(parameters);
                if (!rentas.isEmpty()) {
                    renta = rentas.get(0);
                }    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingresa solo n\u00FAmeros\n"+e, "Error", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(renta == null){
                JOptionPane.showMessageDialog(null, "No se encontr\u00F3 el folio en la base de datos ", "Error", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            for(DetalleRenta detalle : renta.getDetalleRenta()){
                if(detalle.getArticulo().getArticuloId() == this.g_articuloId)
                    articuloEncontrado = true;
            }
            if(!articuloEncontrado)
            {
                JOptionPane.showMessageDialog(null, "Este articulo no se encuentra en el folio :"+renta.getFolio(), "Error", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            this.g_rentaId = renta.getRentaId();
            mostrar_faltantes();
        }else if(this.checkAccidenteLaboral.isSelected() && folio.equals("")){
            this.g_rentaId = 0;
            mostrar_faltantes();
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona solo una opci\u00F3n ", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
     
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        this.asignarFaltante();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkAccidenteLaboralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAccidenteLaboralMouseClicked
        // TODO add your handling code here:
        if(this.checkAccidenteLaboral.isSelected())
            this.txtFolio.setText("");
    }//GEN-LAST:event_checkAccidenteLaboralMouseClicked

    private void txtFolioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == 10)
             this.asignarFaltante();
    }//GEN-LAST:event_txtFolioKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AsignarFaltante dialog = new AsignarFaltante(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkAccidenteLaboral;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDescripcionArticulo;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
