/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobiliario;

import clases.sqlclass;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Carlos Alberto
 */
public class consultar_abonos extends javax.swing.JInternalFrame {

    public static String SQL = "";
    String fecha_sistema = "";
    sqlclass funcion = new sqlclass();
//    sqlclass general = new sqlclass();
    Object[][] dtconduc;
    Object[] datos_combo;

    /**
     * Creates new form consultar_abonos
     */
    public consultar_abonos() {
        funcion.conectate();
        initComponents();
        llenar_combo_chofer();
    }

    public void llenar_combo_chofer() {
        //
//        funcion.conectate();
        datos_combo = funcion.GetColumna("usuarios", "nombre", "SELECT CONCAT(u.`nombre`,\" \", u.`apellidos`)AS nombre FROM usuarios u");
        cmb_usuario.removeAllItems();

        for (int i = 0; i < datos_combo.length - 1; i++) {
            cmb_usuario.addItem(datos_combo[i].toString());

        }
//        funcion.desconecta();

    }

    public void fecha_sistema() {
        Calendar fecha = Calendar.getInstance();
        String mes = Integer.toString(fecha.get(Calendar.MONTH) + 1);
        String dia = Integer.toString(fecha.get(Calendar.DATE));
        String auxMes = null, auxDia = null;

        if (mes.length() == 1) {
            auxMes = "0" + mes;
            fecha_sistema = fecha.get(Calendar.DATE) + "/" + auxMes + "/" + fecha.get(Calendar.YEAR);

            if (dia.length() == 1) {
                auxDia = "0" + dia;
                fecha_sistema = auxDia + "/" + auxMes + "/" + fecha.get(Calendar.YEAR);

            }

        } else {
            fecha_sistema = fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR);
        }
    }

    public void buscar() {
        fecha_sistema();
        SQL = "SELECT "
                + "renta.id_renta, "
                + "renta.folio, "
                + "clientes.nombre AS nombre_cliente, "
                + "clientes.apellidos AS apellidos_cliente, "
                + "renta.descripcion, "
                + "abonos.fecha, "
                + "usuarios.nombre AS nombre_usuario, "
                + "usuarios.apellidos AS apellidos_usuario, "
                + "abonos.abono, "
                + "abonos.comentario, "
                + "abonos.fecha_pago, "
                + "tipo.descripcion AS tipo_pago "
                + "FROM renta renta "
                + "INNER JOIN abonos abonos ON (abonos.id_renta = renta.id_renta) "
                + "INNER JOIN clientes clientes ON (clientes.id_clientes = renta.id_clientes) "                
                + "INNER JOIN tipo_abono tipo ON (tipo.id_tipo_abono = abonos.id_tipo_abono) "
                + "INNER JOIN usuarios usuarios ON (usuarios.id_usuarios = abonos.id_usuario) "                
                + "";
        
        if (check_usuario.isSelected() == true) {
            String id_user = funcion.GetData("id_usuarios", "select id_usuarios from usuarios u where CONCAT(u.`nombre`,\" \", u.`apellidos`)='" + cmb_usuario.getSelectedItem().toString() + "'");
            SQL = SQL + " AND abonos.id_usuario='" + id_user + "'";
        }
        if (check_fechas.isSelected() == true) {

            String fecha_inicial = new SimpleDateFormat("dd/MM/yyyy").format(cmb_fecha_inicial.getDate());
            String fecha_final = new SimpleDateFormat("dd/MM/yyyy").format(cmb_fecha_final.getDate());
            SQL = SQL + " AND STR_TO_DATE(abonos.fecha,'%d/%m/%Y') BETWEEN STR_TO_DATE('" + fecha_inicial + "','%d/%m/%Y')  AND STR_TO_DATE('" + fecha_final + "','%d/%m/%Y')";

        }
        if (check_hoy.isSelected() == true)
            SQL = SQL + " AND STR_TO_DATE(abonos.fecha,'%d/%m/%Y')=   STR_TO_DATE('" + fecha_sistema + "','%d/%m/%Y') ";

    }

    public void mostrar_abonos() {
        abonos ventana = new abonos(null, true);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmb_fecha_inicial = new com.toedter.calendar.JDateChooser();
        cmb_fecha_final = new com.toedter.calendar.JDateChooser();
        check_fechas = new javax.swing.JCheckBox();
        check_hoy = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cmb_usuario = new javax.swing.JComboBox();
        check_usuario = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Abonos");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmb_fecha_inicial.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cmb_fecha_inicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_fecha_inicialMouseClicked(evt);
            }
        });
        cmb_fecha_inicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_fecha_inicialKeyPressed(evt);
            }
        });

        cmb_fecha_final.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        buttonGroup1.add(check_fechas);
        check_fechas.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        check_fechas.setText("Fechas");

        buttonGroup1.add(check_hoy);
        check_hoy.setText("Hoy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_fechas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check_hoy))
                    .addComponent(cmb_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_fecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_fechas)
                    .addComponent(check_hoy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_fecha_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmb_usuario.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cmb_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        check_usuario.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        check_usuario.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(check_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon_32.png"))); // NOI18N
        jButton1.setToolTipText("Buscar por fechas");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_fecha_inicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_fecha_inicialMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_fecha_inicialMouseClicked

    private void cmb_fecha_inicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_fecha_inicialKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_fecha_inicialKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buscar();
        mostrar_abonos();


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox check_fechas;
    private javax.swing.JCheckBox check_hoy;
    private javax.swing.JCheckBox check_usuario;
    public static com.toedter.calendar.JDateChooser cmb_fecha_final;
    public static com.toedter.calendar.JDateChooser cmb_fecha_inicial;
    private javax.swing.JComboBox cmb_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
